name: WorldEvents
author: [Ixpu]
version: '${project.version}'
main: dev.ixpu.worldevents.WorldEvents
api-version: 1.19
description: World event management system
commands:
  worldevents:
    description: WorldEvents plugin commands
    usage: /worldevents reload
